NETWORK_TOPOLOGY_RAW_CODE_TYPE = 'rawCode'
NETWORK_TOPOLOGY_UNPACKED_TYPE = 'unpacked'
NETWORK_TOPOLOGY_RAW_LANGUAGE_TYPE = 'language'
NETWORK_TOPOLOGY_CONNECTION_PARAMETERS_TYPE = 'connectionParameters'
