# Receive
ADD_PROGRAM: str = 'addProgram'
DELETE_PROGRAM: str = 'deleteProgram'
MODIFY_PROGRAM: str = 'modifyProgram'
GET_PROGRAMS: str = 'getPrograms'
GET_RAW_NETWORK_TOPOLOGY: str = 'getRawNetworkTopology'
GET_UNPACKED_NETWORK_TOPOLOGY: str = 'getUnpackedNetworkTopology'
SET_CUSTOM_CONFIG: str = 'setCustomConfig'
GET_CUSTOM_CONFIG: str = 'getCustomConfig'
SET_UP_SIMULATION: str = 'setUpSimulation'
STOP_AND_RESET_SIMULATION: str = 'stopAndResetSimulation'
GET_SIMULATION_STATE: str = 'getSimulationState'
GET_SIMULATION_NODES: str = 'getSimulationNodes'
PERFORM_NODE_ACTION: str = 'performNodeAction'
STREAM_NODE_LOGS: str = 'streamNodeLogs'


# Send
PROGRAMS: str = 'programs'
RAW_NETWORK_TOPOLOGY: str = 'rawNetworkTopology'
UNPACKED_NETWORK_TOPOLOGY: str = 'unpackedNetworkTopology'
CUSTOM_CONFIG: str = 'customConfig'
SIMULATION_STATE: str = 'simulationState'
SIMULATION_NODES: str = 'simulationNodes'
SIMULATION_LOGS: str = 'simulationLogs'
